FROM golang:1.22-alpine AS builder

WORKDIR /app
RUN go mod init app
COPY fullcyle-rocks/ ./
# build the Go application without debug information
RUN go build -ldflags="-s -w" -o app

# Use a minimal base image for the final stage
# This reduces the image size and attack surface
FROM scratch

# Copy the binary from the builder stage
WORKDIR /app
COPY --from=builder /app/app .
ENTRYPOINT ["./app"]